server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: school
          uri: lb://school
          predicates:
            - Path=/api/v1/schools/**

        - id: student
          uri: lb://student
          predicates:
            - Path=/api/v1/students/**
